spring.application.name=pricing
##############################################
# SERVER CONFIG
##############################################
server.port=8082

##############################################
# FEIGN CLIENT CONFIG
##############################################
# URL of your existing Product microservice
# Example: product service runs on port 8080
product.service.url=http://localhost:8080

##############################################
# DATABASE (H2)
##############################################
spring.datasource.url=jdbc:h2:mem:pricingdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# H2 Web Console (OPTIONAL)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.jpa.defer-datasource-initialization=true

##############################################
# LOGGING
##############################################
logging.level.org.springframework=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

##############################################
# JACKSON (optional better serialization)
##############################################
spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false

##############################################
# OPENFEIGN (Spring Cloud)
##############################################
spring.cloud.openfeign.client.config.default.connect-timeout=5000
spring.cloud.openfeign.client.config.default.read-timeout=5000


logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=DEBUG
logging.level.com.example=DEBUG

logging.level.feign.Client=DEBUG
logging.level.feign.Logger=DEBUG
logging.level.org.springframework.cloud.openfeign=DEBUG
logging.level.com.example.pricing.client=DEBUG


# set default feign logger level to FULL
feign.client.config.default.loggerLevel=FULL

# or set for a named client (name in @FeignClient 'name' attribute)
feign.client.config.product-service.loggerLevel=FULL

# logging levels for console output
logging.level.feign=DEBUG

