spring.application.name=spring-integration-sftp

# H2 local persistent database (compatible with H2 2.x)
spring.datasource.url=jdbc:h2:file:./data/batchdb;AUTO_SERVER=TRUE
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver
server.port=8090

# H2 Web Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

# SFTP
sftp.remote.directory=/upload
sftp.local.incoming=sftp-local/incoming
sftp.local.processed=sftp-local/processed
sftp.poll.interval=5000
sftp.host=localhost
sftp.port=2222
sftp.username=harsh
sftp.password=password